site_name: FusionSuite documentation
site_dir: public
repo_url: 'https://github.com/fusionSuite/documentation'
copyright: Copyright © FusionSuite 2022

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 1
      toc_depth: 5
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - attr_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/solid/globe-americas
      link: https:/fusionsuite.org/
      name: Website
    - icon: fontawesome/brands/github
      link: https://github.com/fusionSuite
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FusionSuite
      name: Twitter
# TODO: Add icon for discord
#    - icon: fontawesome/brands/slack
#      link: https://discord.gg/Kj72FwAKTC
#      name: Discord

theme:
  name: material
  features:
    - navigation.top
    - content.code.annotate # (1)

extra_css:
  - stylesheets/extra.css
