site_name: FusionSuite documentation
site_dir: public
repo_url: 'https://github.com/fusionSuite/documentation'
copyright: Copyright © FusionSuite 2022

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 1
      toc_depth: 5
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - attr_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/solid/globe-americas
      link: https:/fusionsuite.org/
      name: Website
    - icon: fontawesome/brands/github
      link: https://github.com/fusionSuite
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FusionSuite
      name: Twitter
# TODO: Add icon for discord
#    - icon: fontawesome/brands/slack
#      link: https://discord.gg/Kj72FwAKTC
#      name: Discord


theme:
  name: material
  features:
    - navigation.top
    - content.code.annotate # (1)
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
